### ISSUE TITLE
Working example for AH_HOST value?

### ISSUE THREAD

**Issue by ReinerNippes** [shadowman-lab/Ansible-PAH#1]
Hi Alex,

could you please provide a working example for the AH_HOST variable? 

I tried several variations. e.g.

url=https://cloud.redhat.com/api/automation-hub/api/galaxy/content/published/
url=https://cloud.redhat.com/api/automation-hub/content/published/
url=https://cloud.redhat.com/api/galaxy/content/published/
url=https://console.redhat.com/api/automation-hub/content/published/

None is working. Either community.crypto is not found or I got an error that no available api version is found. 

There are several pages describing how to connect to the hub, but they are not consistent:
https://console.redhat.com/ansible/automation-hub/token
https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/getting_started_with_automation_hub/proc-configure-automation-hub-server-cli

Thanks,
Reiner

**Comment by adworjan** [comment]
My AH host is my Private Automation hub

url=https://{{yourhubURL}}/

You would have to modify the template if you wanted to use public automation hub since you need to authorize before you connect to the server

[galaxy_server.automation_hub_certified]
url=https://console.redhat.com/api/automation-hub/content/published/
auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
